---
- name: Upgrade packages
  become: true
  apt:
    update_cache: yes
    upgrade: yes
- name: Install Python for ansible
  become: true
  apt:
    update_cache: yes
    name: python
    state: latest
- name: Install nodejs
  become: true
  apt:
    update_cache: yes
    name: nodejs
    state: latest
- name: Install npm
  become: true
  apt:
    update_cache: yes
    name: npm
    state: latest
- name: Install pm2
  become: true
  shell: |
    npm install pm2 -g
