---
- name: create /home/ubuntu/project directory
  become: true
  file:
    path: /home/ubuntu/project
    state: directory
    mode: 0764
    recurse: true
    owner: ubuntu
    group: ubuntu
- name: Untar the zipped folder to the server
  unarchive:
    src: artifact.tar.gz
    dest: ~/project
- name: "Save environment variable to .env file"
  shell: |
    cd ~/project
    touch .env
    echo TYPEORM_CONNECTION="${TYPEORM_CONNECTION}" >> .env
    echo TYPEORM_ENTITIES="${TYPEORM_ENTITIES}" >> .env
    echo TYPEORM_HOST="${TYPEORM_HOST}" >> .env
    echo TYPEORM_PORT="${TYPEORM_PORT}" >> .env
    echo TYPEORM_USERNAME="${TYPEORM_USERNAME}" >> .env
    echo TYPEORM_PASSWORD="${TYPEORM_PASSWORD}" >> .env
    echo TYPEORM_DATABASE="${TYPEORM_DATABASE}" >> .env
    echo TYPEORM_MIGRATIONS="${TYPEORM_MIGRATIONS}" >> .env
    echo TYPEORM_MIGRATIONS_DIR="${TYPEORM_MIGRATIONS_DIR}" >> .env
- name: Start the backend code
  shell: |
    cd ~/project
    npm install
    pm2 stop default
    pm2 start npm -- start
