---
- name: create /home/ubuntu/project directory
  become: true
  file:
    path: /home/ubuntu/project
    state: directory
    mode: 0764
    recurse: true
    owner: ubuntu
    group: ubuntu
- name: Untar the zipped folder to the server
  unarchive:
    src: artifact.tar.gz
    dest: ~/project

- name: Start the backend code
  shell: |
    cd ~/project
    npm install
    pm2 stop default
    pm2 start npm -- start
